// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhv4Y7gbRKXkfEXW_MZxuopdvv8f3Z7jE',
    appId: '1:430538575546:web:aded21501ddc66c581fc83',
    messagingSenderId: '430538575546',
    projectId: 'crypto-list-app-bd3b8',
    authDomain: 'crypto-list-app-bd3b8.firebaseapp.com',
    storageBucket: 'crypto-list-app-bd3b8.appspot.com',
    measurementId: 'G-3Y95LPM7LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1p3PVy9Aa289qOn5d3dCQ13qmyJGYXI0',
    appId: '1:430538575546:android:10e01aeca4c74c3d81fc83',
    messagingSenderId: '430538575546',
    projectId: 'crypto-list-app-bd3b8',
    storageBucket: 'crypto-list-app-bd3b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYxjoj1BLrMPoiASPKZS_gMjyzPWsJu_A',
    appId: '1:430538575546:ios:5eaa01161105227381fc83',
    messagingSenderId: '430538575546',
    projectId: 'crypto-list-app-bd3b8',
    storageBucket: 'crypto-list-app-bd3b8.appspot.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYxjoj1BLrMPoiASPKZS_gMjyzPWsJu_A',
    appId: '1:430538575546:ios:f6eb10891559acef81fc83',
    messagingSenderId: '430538575546',
    projectId: 'crypto-list-app-bd3b8',
    storageBucket: 'crypto-list-app-bd3b8.appspot.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList.RunnerTests',
  );
}
